// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddRawFile(arg1, arg2) {
  return window['go']['main']['App']['AddRawFile'](arg1, arg2);
}

export function AppVersion() {
  return window['go']['main']['App']['AppVersion']();
}

export function CancelRun(arg1) {
  return window['go']['main']['App']['CancelRun'](arg1);
}

export function DataDir() {
  return window['go']['main']['App']['DataDir']();
}

export function DeleteProject(arg1) {
  return window['go']['main']['App']['DeleteProject'](arg1);
}

export function ExportProject(arg1) {
  return window['go']['main']['App']['ExportProject'](arg1);
}

export function ExportProjectFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExportProjectFile'](arg1, arg2, arg3);
}

export function GetAgent() {
  return window['go']['main']['App']['GetAgent']();
}

export function GetDevinModel() {
  return window['go']['main']['App']['GetDevinModel']();
}

export function GetRunLogs(arg1, arg2) {
  return window['go']['main']['App']['GetRunLogs'](arg1, arg2);
}

export function GetRunProjectID(arg1) {
  return window['go']['main']['App']['GetRunProjectID'](arg1);
}

export function GetRunStatus(arg1) {
  return window['go']['main']['App']['GetRunStatus'](arg1);
}

export function GetWorkflowManifest(arg1) {
  return window['go']['main']['App']['GetWorkflowManifest'](arg1);
}

export function IsReady() {
  return window['go']['main']['App']['IsReady']();
}

export function ListDevinModels() {
  return window['go']['main']['App']['ListDevinModels']();
}

export function ListIngestedRaw(arg1) {
  return window['go']['main']['App']['ListIngestedRaw'](arg1);
}

export function ListProjectDir(arg1, arg2, arg3) {
  return window['go']['main']['App']['ListProjectDir'](arg1, arg2, arg3);
}

export function ListRuns() {
  return window['go']['main']['App']['ListRuns']();
}

export function ListWorkflows() {
  return window['go']['main']['App']['ListWorkflows']();
}

export function LogFrontendError(arg1) {
  return window['go']['main']['App']['LogFrontendError'](arg1);
}

export function MCPStatus() {
  return window['go']['main']['App']['MCPStatus']();
}

export function MarkRawIngested(arg1, arg2) {
  return window['go']['main']['App']['MarkRawIngested'](arg1, arg2);
}

export function ReadPersistedRunLogs(arg1, arg2) {
  return window['go']['main']['App']['ReadPersistedRunLogs'](arg1, arg2);
}

export function ReadProjectFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['ReadProjectFile'](arg1, arg2, arg3);
}

export function ReconnectMCP() {
  return window['go']['main']['App']['ReconnectMCP']();
}

export function ResumeRun(arg1, arg2) {
  return window['go']['main']['App']['ResumeRun'](arg1, arg2);
}

export function SelectRawFiles() {
  return window['go']['main']['App']['SelectRawFiles']();
}

export function SetAgent(arg1) {
  return window['go']['main']['App']['SetAgent'](arg1);
}

export function SetDevinModel(arg1) {
  return window['go']['main']['App']['SetDevinModel'](arg1);
}

export function StartRun(arg1, arg2) {
  return window['go']['main']['App']['StartRun'](arg1, arg2);
}

export function ToggleMaximise() {
  return window['go']['main']['App']['ToggleMaximise']();
}

export function WatchRun(arg1) {
  return window['go']['main']['App']['WatchRun'](arg1);
}
