// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddRawFile(arg1, arg2) {
  return window['go']['main']['App']['AddRawFile'](arg1, arg2);
}

export function AddRawText(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddRawText'](arg1, arg2, arg3);
}

export function AddRawURL(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddRawURL'](arg1, arg2, arg3);
}

export function AppVersion() {
  return window['go']['main']['App']['AppVersion']();
}

export function AttachHistoriaFiles(arg1, arg2) {
  return window['go']['main']['App']['AttachHistoriaFiles'](arg1, arg2);
}

export function CancelRun(arg1) {
  return window['go']['main']['App']['CancelRun'](arg1);
}

export function CloneRepoForSnapshot(arg1, arg2) {
  return window['go']['main']['App']['CloneRepoForSnapshot'](arg1, arg2);
}

export function DataDir() {
  return window['go']['main']['App']['DataDir']();
}

export function DeleteProject(arg1) {
  return window['go']['main']['App']['DeleteProject'](arg1);
}

export function DiscardClone(arg1) {
  return window['go']['main']['App']['DiscardClone'](arg1);
}

export function ExportHandoff(arg1) {
  return window['go']['main']['App']['ExportHandoff'](arg1);
}

export function ExportProject(arg1) {
  return window['go']['main']['App']['ExportProject'](arg1);
}

export function ExportProjectFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExportProjectFile'](arg1, arg2, arg3);
}

export function GetAgent() {
  return window['go']['main']['App']['GetAgent']();
}

export function GetClaudeModel() {
  return window['go']['main']['App']['GetClaudeModel']();
}

export function GetCodexModel() {
  return window['go']['main']['App']['GetCodexModel']();
}

export function GetDevinCostSummary() {
  return window['go']['main']['App']['GetDevinCostSummary']();
}

export function GetDevinModel() {
  return window['go']['main']['App']['GetDevinModel']();
}

export function GetRunLogs(arg1, arg2) {
  return window['go']['main']['App']['GetRunLogs'](arg1, arg2);
}

export function GetRunProjectID(arg1) {
  return window['go']['main']['App']['GetRunProjectID'](arg1);
}

export function GetRunStatus(arg1) {
  return window['go']['main']['App']['GetRunStatus'](arg1);
}

export function GetWorkflowManifest(arg1) {
  return window['go']['main']['App']['GetWorkflowManifest'](arg1);
}

export function ImportProject() {
  return window['go']['main']['App']['ImportProject']();
}

export function IsReady() {
  return window['go']['main']['App']['IsReady']();
}

export function ListClaudeModels() {
  return window['go']['main']['App']['ListClaudeModels']();
}

export function ListCodexModels() {
  return window['go']['main']['App']['ListCodexModels']();
}

export function ListDevinModels() {
  return window['go']['main']['App']['ListDevinModels']();
}

export function ListIngestedRaw(arg1) {
  return window['go']['main']['App']['ListIngestedRaw'](arg1);
}

export function ListProjectDir(arg1, arg2, arg3) {
  return window['go']['main']['App']['ListProjectDir'](arg1, arg2, arg3);
}

export function ListProjectRunLogs(arg1) {
  return window['go']['main']['App']['ListProjectRunLogs'](arg1);
}

export function ListRuns() {
  return window['go']['main']['App']['ListRuns']();
}

export function ListWorkflows() {
  return window['go']['main']['App']['ListWorkflows']();
}

export function LocalProjects() {
  return window['go']['main']['App']['LocalProjects']();
}

export function LogFrontendError(arg1) {
  return window['go']['main']['App']['LogFrontendError'](arg1);
}

export function MCPStatus() {
  return window['go']['main']['App']['MCPStatus']();
}

export function MarkRawIngested(arg1, arg2) {
  return window['go']['main']['App']['MarkRawIngested'](arg1, arg2);
}

export function OpenHTMLInBrowser(arg1) {
  return window['go']['main']['App']['OpenHTMLInBrowser'](arg1);
}

export function ProjectsActivity() {
  return window['go']['main']['App']['ProjectsActivity']();
}

export function ReadPersistedRunLogs(arg1, arg2) {
  return window['go']['main']['App']['ReadPersistedRunLogs'](arg1, arg2);
}

export function ReadProjectFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['ReadProjectFile'](arg1, arg2, arg3);
}

export function ReconnectMCP() {
  return window['go']['main']['App']['ReconnectMCP']();
}

export function RemoveHistoriaAttachment(arg1, arg2, arg3) {
  return window['go']['main']['App']['RemoveHistoriaAttachment'](arg1, arg2, arg3);
}

export function RemoveRawSource(arg1, arg2) {
  return window['go']['main']['App']['RemoveRawSource'](arg1, arg2);
}

export function ResetIngestedRaw(arg1) {
  return window['go']['main']['App']['ResetIngestedRaw'](arg1);
}

export function ResumeRun(arg1, arg2) {
  return window['go']['main']['App']['ResumeRun'](arg1, arg2);
}

export function RetryStartup() {
  return window['go']['main']['App']['RetryStartup']();
}

export function SelectRawFiles() {
  return window['go']['main']['App']['SelectRawFiles']();
}

export function SelectRawFilesFiltered(arg1, arg2, arg3) {
  return window['go']['main']['App']['SelectRawFilesFiltered'](arg1, arg2, arg3);
}

export function SelectRepoDir() {
  return window['go']['main']['App']['SelectRepoDir']();
}

export function SetAgent(arg1) {
  return window['go']['main']['App']['SetAgent'](arg1);
}

export function SetClaudeModel(arg1) {
  return window['go']['main']['App']['SetClaudeModel'](arg1);
}

export function SetCodexModel(arg1) {
  return window['go']['main']['App']['SetCodexModel'](arg1);
}

export function SetDevinModel(arg1, arg2) {
  return window['go']['main']['App']['SetDevinModel'](arg1, arg2);
}

export function ShowWarningDialog(arg1, arg2) {
  return window['go']['main']['App']['ShowWarningDialog'](arg1, arg2);
}

export function StartRun(arg1, arg2) {
  return window['go']['main']['App']['StartRun'](arg1, arg2);
}

export function StartupStatus() {
  return window['go']['main']['App']['StartupStatus']();
}

export function ToggleMaximise() {
  return window['go']['main']['App']['ToggleMaximise']();
}

export function WatchRun(arg1) {
  return window['go']['main']['App']['WatchRun'](arg1);
}

export function WikiStaleSources(arg1) {
  return window['go']['main']['App']['WikiStaleSources'](arg1);
}
