// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddRawFile(arg1:string,arg2:string):Promise<string>;

export function AppVersion():Promise<string>;

export function CancelRun(arg1:string):Promise<string>;

export function DataDir():Promise<string>;

export function DeleteProject(arg1:string):Promise<void>;

export function ExportProject(arg1:string):Promise<string>;

export function ExportProjectFile(arg1:string,arg2:string,arg3:string):Promise<string>;

export function GetAgent():Promise<string>;

export function GetDevinCostSummary():Promise<string>;

export function GetDevinModel():Promise<string>;

export function GetRunLogs(arg1:string,arg2:string):Promise<string>;

export function GetRunProjectID(arg1:string):Promise<string>;

export function GetRunStatus(arg1:string):Promise<string>;

export function GetWorkflowManifest(arg1:string):Promise<string>;

export function IsReady():Promise<boolean>;

export function ListDevinModels():Promise<string>;

export function ListIngestedRaw(arg1:string):Promise<string>;

export function ListProjectDir(arg1:string,arg2:string,arg3:string):Promise<string>;

export function ListProjectRunLogs(arg1:string):Promise<string>;

export function ListRuns():Promise<string>;

export function ListWorkflows():Promise<string>;

export function LogFrontendError(arg1:string):Promise<void>;

export function MCPStatus():Promise<string>;

export function MarkRawIngested(arg1:string,arg2:string):Promise<string>;

export function ReadPersistedRunLogs(arg1:string,arg2:string):Promise<string>;

export function ReadProjectFile(arg1:string,arg2:string,arg3:string):Promise<string>;

export function ReconnectMCP():Promise<string>;

export function ResumeRun(arg1:string,arg2:string):Promise<string>;

export function SelectRawFiles():Promise<string>;

export function SetAgent(arg1:string):Promise<string>;

export function SetDevinModel(arg1:string,arg2:string):Promise<string>;

export function ShowWarningDialog(arg1:string,arg2:string):Promise<void>;

export function StartRun(arg1:string,arg2:string):Promise<string>;

export function ToggleMaximise():Promise<void>;

export function WatchRun(arg1:string):Promise<void>;
